./scripts/b_unique_con_3.sh
./scripts/b_unique_con_5.sh
./scripts/b_unique_con_7.sh
./scripts/b_unique_con_9.sh
./scripts/b_asc_con_3.sh
./scripts/b_asc_con_5.sh
./scripts/b_asc_con_7.sh
./scripts/b_asc_con_9.sh
./scripts/b_des_con_3.sh
./scripts/b_des_con_5.sh
./scripts/b_des_con_7.sh
./scripts/b_des_con_9.sh
./scripts/b_unique_asc_con_3.sh
./scripts/b_unique_asc_con_5.sh
./scripts/b_unique_asc_con_7.sh
./scripts/b_unique_asc_con_9.sh
./scripts/b_unique_con_ra_3.sh
./scripts/b_unique_con_ra_5.sh
./scripts/b_unique_con_ra_7.sh
./scripts/b_unique_con_ra_9.sh
./scripts/b_asc_con_ra_3.sh
./scripts/b_asc_con_ra_5.sh
./scripts/b_asc_con_ra_7.sh
./scripts/b_asc_con_ra_9.sh
./scripts/b_des_con_ra_3.sh
./scripts/b_des_con_ra_5.sh
./scripts/b_des_con_ra_7.sh
./scripts/b_des_con_ra_9.sh
./scripts/b_unique_asc_con_ra_3.sh
./scripts/b_unique_asc_con_ra_5.sh
./scripts/b_unique_asc_con_ra_7.sh
./scripts/b_unique_asc_con_ra_9.sh
./scripts/b_stack_con_3.sh
./scripts/b_stack_con_5.sh
./scripts/b_stack_con_7.sh
./scripts/b_stack_con_9.sh